name: mongo-sharding-repl

services:

  configSrv1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv1
    restart: always
    ports:
      - "27019:27019"
    command: mongod --configsvr --replSet config_rs --port 27019 --bind_ip_all
    volumes:
      - config1_data:/data/db

  configSrv2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv2
    restart: always
    ports:
      - "27020:27019"
    command: mongod --configsvr --replSet config_rs --port 27019 --bind_ip_all
    volumes:
      - config2_data:/data/db

  configSrv3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv3
    restart: always
    ports:
      - "27021:27019"
    command: mongod --configsvr --replSet config_rs --port 27019 --bind_ip_all
    volumes:
      - config3_data:/data/db

  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-1
    restart: always
    ports:
      - "27018:27018"
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --bind_ip_all
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-2
    restart: always
    ports:
      - "27022:27018"
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --bind_ip_all
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-3
    restart: always
    ports:
      - "27023:27018"
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --bind_ip_all
    volumes:
      - shard1_3_data:/data/db

  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-1
    restart: always
    ports:
      - "27024:27018"
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --bind_ip_all
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-2
    restart: always
    ports:
      - "27025:27018"
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --bind_ip_all
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-3
    restart: always
    ports:
      - "27026:27018"
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --bind_ip_all
    volumes:
      - shard2_3_data:/data/db

  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27017:27017"
    depends_on:
      - configSrv1
      - configSrv2
      - configSrv3
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    command: mongos --configdb config_rs/configSrv1:27019,configSrv2:27019,configSrv3:27019 --port 27017 --bind_ip_all

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongos_router
    environment:
      MONGODB_URL: "mongodb://mongos_router:27017"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config1_data:
  config2_data:
  config3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
